export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST"
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS"
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL"
export const CLEAR_ERRORS ='CLEAR_ERRORS'

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST"
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS"
export const PRODUCT_DETAILS_FAIL =    "PRODUCT_DETAILS_FAIL"

export const CATEGORY_PRODUCT_REQUEST = 'CATEGORY_PRODUCT_REQUEST';
export const CATEGORY_PRODUCT_SUCCESS = 'CATEGORY_PRODUCT_SUCCESS';
export const CATEGORY_PRODUCT_FAIL = 'CATEGORY_PRODUCT_FAIL';